# Generated by Django 2.0.4 on 2018-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockadvisor', '0002_auto_20180405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
